[package]
name = "ecies"
version = "0.1.0"
authors = ["Weiliang Li <to.be.impressive@gmail.com"]
edition = "2018"

[dependencies]
secp256k1 = "0.15"
crypto = { package = "rust-crypto", version = "0.2"}
hex ="0.3"
